"""add_connects_used_to_jobs

Revision ID: 4a725ee46644
Revises: dd1eeec8ea78
Create Date: 2026-01-12 23:45:21.866521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a725ee46644'
down_revision = 'dd1eeec8ea78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('connects_used', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'connects_used')
    # ### end Alembic commands ###
